using HM2.AutoGenerated;
using HM2.GameSolve.Interfaces;
using HM2.GameSolve.Structures;
using HM2.IoCs;
using HM2.MovableObject;
using System;
using System.IO;

namespace HM2
{
    class Program
    {
        static void Main(string[] args)
        {


        }
    }
}
